language: ruby
rvm:
    - "2.2.1"
install:
    - bundle install
script:
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake spec
branches:
    only:
        - travis_ci
